version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
  app:
    build: .
    container_name: gestion-sav-service
    restart: always
    environment:
      MONGODB_URI: mongodb://root:example@mongodb:27017/gestion_sav?authSource=admin
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
